-- Hyprland Lua config converted from hyprland.conf for Hyprland 0.55+.
-- See https://wiki.hypr.land/Configuring/Start/

-- Remove this commented line to keep the generated-config warning disabled.
-- hl.config({ autogenerated = true })

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({ output = "eDP-1", mode = "1920x1080@60.052", position = "0x0", scale = 1 })
-- hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60", position = "0x0", scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60", position = "0x0", scale = 1, mirror = "eDP-1" })
hl.monitor({ output = "DP-1", mode = "2560x1440@99.95", position = "1920x0", scale = 1 })

---------------------------
---- XWAYLAND / SOURCE ----
---------------------------

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Source a file (multi-file configs).
-- require("myColors")

-------------------
---- AUTOSTART ----
-------------------

-- Execute your favorite apps at launch.
-- hl.on("hyprland.start", function()
--     hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("$HOME/PATH/hyprland_autostart.sh")
    hl.exec_cmd("hyprctl setcursor rose-pine-hyprcursor 36")
    -- hl.exec_cmd("hyprctl setcursor rose-pine-hyprcursor-dawn 36")
    hl.exec_cmd("hyprpm reload -n")
end)

--------------------------------
---- ENVIRONMENT VARIABLES -----
--------------------------------

hl.env("XCURSOR_SIZE", "48")
hl.env("XCURSOR_THEME", "BreezeX-RosePine-Linux")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "48")
-- hl.env("GTK_THEME", "Arc-Dark")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("WLR_NO_HARDWARE_CURSORS", "1")
hl.env("EDITOR", "nvim")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("LIBVA_DRIVER_NAME", "iHD")
hl.env("MOZ_DRM_DEVICE", "/dev/dri/renderD128")
hl.env("GDK_SCALE", "1")
hl.env("GDK_DPI_SCALE", "1")
hl.env("GDK_BACKEND", "wayland")

-- Use intel gpu.
hl.env("AQ_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0")

----------------
---- INPUT -----
----------------

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        numlock_by_default = true,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 15,
        border_size = 3,
        col = {
            active_border = { colors = { "rgba(d7875fff)", "rgba(dfafafff)" }, angle = 45 },
            inactive_border = "rgba(262a35aa)",
        },
        layout = "dwindle",
    },

    decoration = {
        rounding = 15,
        blur = {
            enabled = true,
            size = 10,
            passes = 3,
        },
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
    },

    animations = {
        enabled = true,
    },
})

-- Some default animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "default", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 8, bezier = "myBezier", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 8, bezier = "myBezier", style = "slidevert" })

-----------------
---- LAYOUTS ----
-----------------

hl.config({
    dwindle = {
        -- pseudotile = true, -- master switch for pseudotiling; bound below to mainMod + P.
        preserve_split = true, -- You probably want this.
        special_scale_factor = 0.6,
    },
    master = {
        -- new_status = "slave",
    },
})

hl.config({
    group = {
        col = {
            border_active = { colors = { "rgba(d7875fff)", "rgba(dfafafff)" }, angle = 45 },
            border_inactive = "rgba(262a35aa)",
        },
        groupbar = {
            font_family = "Iosevka",
            font_size = 16,
            text_color = "rgba(ffffffff)",
            render_titles = true,
            gradients = true,
            col = {
                active = { colors = { "rgba(d7875faa)", "rgba(dfafafaa)" }, angle = 45 },
                inactive = { colors = { "rgba(262a3599)", "rgba(262a3555)" }, angle = 90 },
            },
        },
    },
})

------------------
---- GESTURES ----
------------------

-- Removed 0.54-style options kept as a commented reference.
-- hl.config({ gestures = { workspace_swipe = true, workspace_swipe_fingers = 3 } })

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- Example per-device config.
-- hl.device({ name = "epic-mouse-v1", sensitivity = -0.5 })

-------------
---- MISC ---
-------------

hl.config({
    misc = {
        disable_hyprland_logo = true,
        enable_swallow = true,
        swallow_regex = "^(kitty)$",
        swallow_exception_regex = "(^zsh.*|.*nvim.*|^wev$|.*cgx.*)",
    },
    debug = {
        disable_logs = false,
    },
})

-----------------
---- PLUGINS ----
-----------------

local function has_config_key(key)
    local ok, _, err = pcall(hl.get_config, key)
    return ok and err == nil
end

if has_config_key("plugin.hycov.overview_gappo") then
    hl.config({
        plugin = {
            hycov = {
            overview_gappo = 100,
            overview_gappi = 50,
            enable_hotarea = 1,
            hotarea_monitor = "all",
            hotarea_pos = 1,
            hotarea_size = 10,
            swipe_fingers = 4,
            move_focus_distance = 100,
            enable_gesture = 1,
            disable_workspace_change = 0,
            disable_spawn = 0,
            auto_exit = 1,
            auto_fullscreen = 0,
            only_active_workspace = 0,
            only_active_monitor = 0,
            enable_alt_release_exit = 1,
            -- alt_replace_key = "Alt_L",
            alt_toggle_auto_next = 1,
            click_in_cursor = 1,
            height_of_titlebar = 0,
        },
        },
    })
end

if has_config_key("plugin.overview.onBottom") then
    hl.config({
        plugin = {
            overview = {
            onBottom = false,
            panelColor = "rgba(262a35aa)",
            affectStrut = true,
            hideOverlayLayers = true,
            gapsIn = 50,
            gapsOut = 100,
            hideTopLayers = true,
            exitOnClick = true,
            workspaceActiveBorder = "rgba(223,175,175,1.0)",
            showEmptyWorkspace = false,
            showNewWorkspace = false,
        },
        },
    })
end

if has_config_key("plugin.hyprbars.bar_height") then
    hl.config({
        plugin = {
            hyprbars = {
            bar_height = 24,
            bar_color = "rgba(303446bb)",
            bar_text_align = "center",
            bar_precedence_over_border = true,
            bar_text_font = "Iosevka Nerd Font",
            bar_text_size = 16,
            bar_part_of_window = true,
            ["hyprbars-button"] = {
                "rgba(262a3500), 24,  , hyprctl dispatch killactive",
                "rgba(262a3500), 24,  , hyprctl dispatch fullscreen 1",
            },
        },
        },
    })
end

----------------------
---- WINDOW RULES ----
----------------------

-- Example windowrule v1.
-- hl.window_rule({ match = { class = "^(kitty)$" }, float = true })
-- Example windowrule v2.
-- hl.window_rule({ match = { class = "^(kitty)$", title = "^(kitty)$" }, float = true })

hl.window_rule({
    name = "logout",
    match = { title = "^(wlogout)$" },
    no_anim = true,
    float = true,
})

hl.window_rule({
    name = "keepass",
    match = { title = "^(Generate Password)$" },
    no_anim = true,
    float = true,
})

------------------------
---- WORKSPACE RULES ---
------------------------

hl.workspace_rule({ workspace = "special:scratchpad", on_created_empty = "kitty" })
hl.workspace_rule({ workspace = "1", monitor = "DP-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "3", monitor = "DP-1", persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "eDP-1", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "eDP-1", persistent = true })
hl.workspace_rule({ workspace = "6", monitor = "eDP-1", persistent = false })
hl.workspace_rule({ workspace = "7", monitor = "DP-1", persistent = false })
hl.workspace_rule({ workspace = "8", monitor = "DP-1", persistent = false })
hl.workspace_rule({ workspace = "9", monitor = "DP-1", persistent = false })
hl.workspace_rule({ workspace = "10", monitor = "DP-1", persistent = false })

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + ALT + Q", hl.dsp.exit())
hl.bind(mainMod .. " + SHIFT + ESCAPE", hl.dsp.exec_cmd("$HOME/PATH/launch_waybar.sh"))
-- hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd("$HOME/PATH/lock_screen_off.sh"))
hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("kitty -e yazi"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("pcmanfm-qt"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd("thunderbird"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("vesktop")) -- Discord client.
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd("rofi -show drun -location 0 -theme ~/.config/rofi/themes/Serenity -config ~/.config/rofi/config -show-icons"))
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.exec_cmd("DRI_PRIME=pci-0000_01_00_0 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia rofi -show drun -xoffset 100 -yoffset 200 -theme ~/.config/rofi/themes/Serenity -show-icons"))
hl.bind(mainMod .. " + ESCAPE", hl.dsp.exec_cmd("killall wlogout; wlogout"))
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("qalculate-gtk"))
-- hl.bind(mainMod .. " + SUPER_L", hl.dsp.exec_cmd("rofi -show drun -theme ~/.config/rofi/themes/launchpad.rasi -config ~/.config/rofi/config-launchpad -show-icons"), { release = true })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- dwindle.
hl.bind(mainMod .. " + F", hl.dsp.layout("togglesplit")) -- dwindle.
hl.bind(mainMod .. " + T", hl.dsp.workspace.toggle_special("scratchpad"))
hl.bind(mainMod .. " + F11", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
-- Legacy plugin dispatchers kept as comments from hyprland.conf.
-- bind = ALT, tab, hycov:toggleoverview
-- hl.bind("ALT + tab", hl.dsp.workspace.toggle_special("overview"))
-- hl.bind("ALT + tab", hl.dsp.focus({ workspace = "e+1" }))
-- hl.bind("ALT + tab", hl.dsp.exec_cmd("sleep 1 && hyprctl dispatch overview:close"), { release = true })
-- bind = ALT + SHIFT, tab, overview:open
-- hl.bind("ALT + SHIFT + tab", hl.dsp.focus({ workspace = "e-1" }))
-- hl.bind("ALT + SHIFT + tab", hl.dsp.exec_cmd("sleep 1 && hyprctl dispatch overview:close"), { release = true })

-- Move focus with mainMod + vim keys.
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "d" }))

-- Cycle focus with mainMod + C and mainMod + SHIFT + C.
hl.bind(mainMod .. " + C", hl.dsp.window.cycle_next())
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.cycle_next({ next = false }))

-- Move windows with mainMod + vim keys.
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))

-- Window grouping.
hl.bind(mainMod .. " + G", hl.dsp.group.toggle())
hl.bind(mainMod .. " + ALT + H", hl.dsp.window.move({ into_group = "l" }))
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.move({ into_group = "r" }))
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.move({ into_group = "u" }))
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.move({ into_group = "d" }))
hl.bind(mainMod .. " + TAB", hl.dsp.group.next())
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.group.prev())
hl.bind(mainMod .. " + ALT + SHIFT + H", hl.dsp.window.move({ out_of_group = "l" }))
hl.bind(mainMod .. " + ALT + SHIFT + L", hl.dsp.window.move({ out_of_group = "r" }))
hl.bind(mainMod .. " + ALT + SHIFT + K", hl.dsp.window.move({ out_of_group = "u" }))
hl.bind(mainMod .. " + ALT + SHIFT + J", hl.dsp.window.move({ out_of_group = "d" }))

-- Window resizing.
hl.bind(mainMod .. " + CTRL + H", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + L", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(mainMod .. " + CTRL + K", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(mainMod .. " + CTRL + J", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- Switch workspaces with mainMod + [0-9].
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
-- hl.bind(mainMod .. " + T", hl.dsp.focus({ workspace = "special" }))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.move({ workspace = "special:scratchpad" }))

-- Move active window to a workspace with mainMod + Keypad [0-9].
hl.bind(mainMod .. " + KP_End", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + KP_Down", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + KP_Next", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + KP_Left", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + KP_Begin", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + KP_Right", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + KP_Home", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + KP_Up", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + KP_Prior", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + KP_Insert", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + Keypad [0-9].
hl.bind(mainMod .. " + SHIFT + KP_End", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + KP_Down", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + KP_Next", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + KP_Left", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + KP_Begin", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + KP_Right", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + KP_Home", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + KP_Up", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + KP_Prior", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + KP_Insert", hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll.
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging.
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume and media control.
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("$HOME/PATH/volume.sh --inc"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("$HOME/PATH/volume.sh --dec"), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("$HOME/PATH/volume.sh --toggle-mic"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("$HOME/PATH/volume.sh --toggle"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- Display backlight control from keyboard made for Windows/Linux.
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("$HOME/PATH/backlight.sh --inc"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("$HOME/PATH/backlight.sh --dec"))
-- Display backlight control from keyboard made for Mac.
hl.bind("XF86Launch5", hl.dsp.exec_cmd("$HOME/PATH/backlight.sh --dec"), { repeating = true })
hl.bind("XF86Launch6", hl.dsp.exec_cmd("$HOME/PATH/backlight.sh --inc"), { repeating = true })

-- Additional applications.
-- zsh -i workaround for nvim to detect path from .zshrc.
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd('kitty -e zsh -i -c "nvim"'))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("emacs"))
-- Emoji menu.
hl.bind(mainMod .. " + EQUAL", hl.dsp.exec_cmd("rofimoji --action copy clipboard"))
-- Clipboard history.
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("rofi -modi clipboard:$HOME/PATH/cliphist-rofi.sh -show clipboard -theme ~/.config/rofi/themes/Serenity -show-icons"))
-- Delete from clipboard history.
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list| rofi -dmenu -theme ~/.config/rofi/themes/Serenity -show-icons | cliphist delete"))

-- Swaync key binds.
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("swaync-client -t"))

-- Screenshot.
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("grimblast --notify copysave screen"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("grimblast --notify copysave area"))
hl.bind("Print", hl.dsp.exec_cmd("grimblast --notify copysave screen"))

-- mpdevil.
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("mpdevil"))

-- Hints for keyboard navigation.
-- Waybar needs to be killed as it offsets hints layer.
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("$HOME/.local/bin/hints"))
