return {
	"catppuccin/nvim",
	name = "catppuccin",
	priority = 1000,
	opts = {
		transparent_background = true,
		integrations = {
			treesitter = true,
            barbar= true,
			telescope = true,
		},
		float = {
			transparent = true,
		},
		telescope = {
			enabled = true,
			style = "classic",
		},
		color_overrides = {
			all = {
				base = "#eff1f6",
				text = "#ffffff",
				mantle = "#dfafaf",
				crust = "#d7875f",
				blue = "#7e99d6",
				red = "#E78284",
				lavender = "#B4BEFE",
				mauve = "#CA9EE6",
				sky = "#85C1DC",
				green = "#A6E3A1",
				peach = "#ffd3ac",
				teal = "#3EBB9E",
				yellow = "#f9e2b0",
				codeblock = "#51555d",
				sapphire = "#74c7ed",
				rosewater = "#f5e0dd",
				flamingo = "#f2cdce",
				pink = "#f5c2e8",
				maroon = "#eba0ad",
				overlay0 = "#9ca0b1",
				overlay1 = "#8c8fa2",
				overlay2 = "#7c7f94",
				subtext0 = "#6c6f86",
				subtext1 = "#5c5f78",
				surface0 = "#262a35",
				surface1 = "#3c3f4a",
				surface2 = "#acb0bf",
			},
			latte = {},
			frappe = {},
			macchiato = {},
			mocha = {},
		},
		custom_highlights = function(colors)
			return {
				Comment = { fg = colors.mantle },
				TabLineSel = { fg = "#ff0000" },
				LineNr = { fg = colors.text },
				NonText = { fg = colors.text },
				Whitespace = { fg = "#c9cacc" },
				-- Diff highlights
				DiffAdd = { bg = "#465850" },
				DiffChange = { bg = "#5c5453" },
				DiffDelete = { bg = "#60444d" },
				DiffText = { bg = "#4f4761" },

				-- Telescope
				TelescopeSelection = { bg = colors.surface1 },

				-- nvim-notify highlights
				NotifyERRORBorder = { fg = colors.red },
				NotifyWARNBorder = { fg = colors.crust },
				NotifyINFOBorder = { fg = colors.green },
				NotifyDEBUGBorder = { fg = "#8B8B8B" },
				NotifyTRACEBorder = { fg = colors.codeblock },

				NotifyERRORIcon = { fg = colors.red },
				NotifyWARNIcon = { fg = colors.crust },
				NotifyINFOIcon = { fg = colors.green },
				NotifyDEBUGIcon = { fg = "#8B8B8B" },
				NotifyTRACEIcon = { fg = colors.mauve },

				NotifyERRORTitle = { fg = colors.red },
				NotifyWARNTitle = { fg = colors.crust },
				NotifyINFOTitle = { fg = colors.green },
				NotifyDEBUGTitle = { fg = "#8B8B8B" },
				NotifyTRACETitle = { fg = colors.crust },

				NotifyERRORBody = { link = "Normal" },
				NotifyWARNBody = { link = "Normal" },
				NotifyINFOBody = { link = "Normal" },
				NotifyDEBUGBody = { link = "Normal" },
				NotifyTRACEBody = { link = "Normal" },

				-- Markview highlights
				MarkviewPalette0 = { fg = colors.text, bg = "none", bold = true },
				MarkviewPalette1 = { fg = colors.red, bg = "#60444d", bold = true },
				MarkviewPalette2 = { fg = colors.lavender, bg = "#4a4f67", bold = true },
				MarkviewPalette3 = { fg = colors.mauve, bg = "#4f4761", bold = true },
				MarkviewPalette4 = { fg = colors.green, bg = "#465850", bold = true },
				MarkviewPalette5 = { fg = colors.sky, bg = "#3e505f", bold = true },
				MarkviewPalette6 = { fg = colors.peach, bg = "#5c5453", bold = true },
				MarkviewPalette1Sign = { fg = colors.red, bg = "#60444d", bold = true },
				MarkviewPalette2Sign = { fg = colors.lavender, bg = "#4a4f67", bold = true },
				MarkviewPalette3Sign = { fg = colors.mauve, bg = "#4f4761", bold = true },
				MarkviewPalette4Sign = { fg = colors.green, bg = "#465850", bold = true },
				MarkviewPalette5Sign = { fg = colors.sky, bg = "#3e505f", bold = true },
				MarkviewPalette6Sign = { fg = colors.peach, bg = "#5c5453", bold = true },
				MarkviewCode = { bg = colors.codeblock },
				MarkviewInlineCode = { fg = colors.text, bg = colors.surface1 },
				MarkviewHyperlink = { fg = colors.crust, underline = true },
				MarkviewTableHeader = { fg = colors.mantle, bold = true },
				["@punctuation.bracket"] = { fg = colors.text },
				["@punctuation.delimiter"] = { fg = colors.peach },
			}
		end,
	},
}
